//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Table
    {
        public int Employee_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Designation_Id { get; set; }
        public string Sallery { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public string Profile_Img { get; set; }
        public Nullable<int> Qualification_Id { get; set; }
        public Nullable<System.DateTime> Crd_Date { get; set; }
        public string Crd_By { get; set; }
        public Nullable<System.DateTime> Lmd_Date { get; set; }
        public string Lmd_By { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
