//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Tbl
    {
        public int Event_Id { get; set; }
        public string Event_Tittle { get; set; }
        public string Event_Description { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Fee { get; set; }
        public string Total_Sheats { get; set; }
        public string Lectures { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Crd_Date { get; set; }
        public string Crd_By { get; set; }
        public Nullable<System.DateTime> Lmd_Date { get; set; }
        public string Lmd_By { get; set; }
        public bool IsActive { get; set; }
        public bool ISDeleted { get; set; }
    }
}
