//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APSD_DatabaseEntities : DbContext
    {
        public APSD_DatabaseEntities()
            : base("name=APSD_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_Tbl> Address_Tbl { get; set; }
        public virtual DbSet<Course_Tbl> Course_Tbl { get; set; }
        public virtual DbSet<Designation_Tbl> Designation_Tbl { get; set; }
        public virtual DbSet<Education_Tbl> Education_Tbl { get; set; }
        public virtual DbSet<Employee_Table> Employee_Table { get; set; }
        public virtual DbSet<Event_Tbl> Event_Tbl { get; set; }
        public virtual DbSet<FeedBack_Tbl> FeedBack_Tbl { get; set; }
        public virtual DbSet<Gallery_Tbl> Gallery_Tbl { get; set; }
        public virtual DbSet<Login_Tbl> Login_Tbl { get; set; }
        public virtual DbSet<Qualification_Tbl> Qualification_Tbl { get; set; }
        public virtual DbSet<Student_Tbl> Student_Tbl { get; set; }
    }
}
