//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Tbl
    {
        public int Student_Id { get; set; }
        public Nullable<int> Enrollment_Id { get; set; }
        public string Student_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string College { get; set; }
        public string Branch { get; set; }
        public string Year { get; set; }
        public string Aadhaar { get; set; }
        public Nullable<int> Technologies_Id { get; set; }
        public string Registration_Fee { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public string Program { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public Nullable<System.DateTime> Crd_Date { get; set; }
        public string Crd_By { get; set; }
        public Nullable<System.DateTime> Lmd_Date { get; set; }
        public string Lmd_By { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
